[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    Referrer-Policy = "no-referrer-when-downgrade"

[[headers]]
  for = "/ads.txt"
  [headers.values]
    Content-Type = "text/plain; charset=utf-8"

[[redirects]]
  from = "https://www.skyhitmedia.com/*"
  to = "https://skyhitmedia.com/:splat"
  status = 301
  force = true
